apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::169810528182:role/eksctl-expense-1-nodegroup-expense-NodeInstanceRole-SIH0OKXuQgel
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::169810528182:user/lakshmi
      username: lakshmi
    - groups:
      - expense-admin
      userarn: arn:aws:iam::169810528182:user/venkatesh
      username: venkatesh 
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-07T00:11:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2333"
  uid: a45639ae-0ece-4fc5-98b7-feca98b5e980
