apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::169810528182:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-pB2RGCPYvOeu
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::169810528182:user/lakshmi
      username: lakshmi
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-08T07:16:50Z"
  name: aws-auth
  namespace: kube-system
  uid: f6f2ffec-89c9-4c09-b71c-1ad5e9cc9a7e
